CREATE TABLE IF NOT EXISTS players (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  nickname VARCHAR(255),
  country VARCHAR(100),
  position VARCHAR(100),
  biography TEXT
);